In [15]:
!pip install roboflow

In [16]:
from IPython.display import Image,clear_output

In [24]:
from roboflow import Roboflow

rf = Roboflow(api_key="P5uluqx7HFjXZKM1FSF0")
project = rf.workspace().project("acne_detection")
model = project.version(1).model

loading Roboflow workspace...
loading Roboflow project...


In [25]:
# infer on a local imag
dict=(model.predict(r"C:\Users\Akshaya\MACHINE LEARNING PROJECTS\acne robo\eg2.jpeg", confidence=50, overlap=50).json())

In [6]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [19]:
print(dict)

{'predictions': [{'x': 880, 'y': 381, 'width': 45, 'height': 46, 'confidence': 0.5586880445480347, 'class': 'acne', 'class_id': 0, 'image_path': 'C:\\Users\\Akshaya\\MACHINE LEARNING PROJECTS\\acne robo\\eg2.jpeg', 'prediction_type': 'ObjectDetectionModel'}, {'x': 879, 'y': 471, 'width': 31, 'height': 30, 'confidence': 0.5026295185089111, 'class': 'acne', 'class_id': 0, 'image_path': 'C:\\Users\\Akshaya\\MACHINE LEARNING PROJECTS\\acne robo\\eg2.jpeg', 'prediction_type': 'ObjectDetectionModel'}], 'image': {'width': '963', 'height': '1280'}}


In [20]:
count = 0
for x in dict:
    if isinstance(dict[x], list):
        count += len(dict[x])

print(count)

2


In [21]:

# Import the necessary libraries
from PIL import Image
from numpy import asarray
 
 
# load the image and convert into 
# numpy array
img = Image.open(r"C:\Users\Akshaya\MACHINE LEARNING PROJECTS\acne robo\eg2.jpeg")
numpydata = asarray(img)
 
# data
print(numpydata)

[[[ 14  22  25]
  [ 12  20  23]
  [ 10  18  21]
  ...
  [ 99  86  70]
  [ 99  86  70]
  [100  87  71]]

 [[ 13  21  24]
  [ 12  20  23]
  [ 10  18  21]
  ...
  [ 95  82  66]
  [ 96  83  67]
  [ 96  83  67]]

 [[ 11  19  22]
  [ 10  18  21]
  [  9  17  20]
  ...
  [ 97  84  68]
  [ 97  84  68]
  [ 97  84  68]]

 ...

 [[107  35  49]
  [109  37  51]
  [112  40  54]
  ...
  [ 98  84  75]
  [ 98  84  75]
  [ 97  83  74]]

 [[103  31  45]
  [106  34  48]
  [110  38  52]
  ...
  [ 98  84  75]
  [ 98  84  75]
  [ 98  84  75]]

 [[100  28  42]
  [104  32  46]
  [109  37  51]
  ...
  [ 97  83  74]
  [ 97  83  74]
  [ 97  83  74]]]


In [22]:
import cv2
image=r"C:\Users\Akshaya\MACHINE LEARNING PROJECTS\acne robo\WhatsApp Image 2023-11-27 at 14.34.40.jpeg"
predictions = dict

for bounding_box in predictions["predictions"]:
    x0 = bounding_box['x'] - bounding_box['width'] / 2
    x1 = bounding_box['x'] + bounding_box['width'] / 2
    y0 = bounding_box['y'] - bounding_box['height'] / 2
    y1 = bounding_box['y'] + bounding_box['height'] / 2
    
    start_point = (int(x0), int(y0))
    end_point = (int(x1), int(y1))
    cv2.rectangle(numpydata, start_point, end_point, color=(0,255,0), thickness=2)
   
cv2.imwrite("example_with_bounding_boxes.jpg",numpydata)

True

In [23]:
if count<5:
    print("Mild acne")
elif count<20:
    print("Moderate acne")
elif count<50:
    print("Severe acne")
elif count>100:
    print("Extremely Severe acne")
else:
    print("No ance of clear face")

Mild acne
